// <auto-generated />
using System;
using BlazorWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("BlazorWebApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new { Id = 1, City = "New York", Company = "TechCorp", CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "john.anderson@example.com", FirstName = "John", LastName = "Anderson", Phone = "+1-555-0101" },
                        new { Id = 2, City = "San Francisco", Company = "InnovateLabs", CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "sarah.bennett@example.com", FirstName = "Sarah", LastName = "Bennett", Phone = "+1-555-0102" },
                        new { Id = 3, City = "Los Angeles", Company = "DataSystems", CreatedAt = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "michael.chen@example.com", FirstName = "Michael", LastName = "Chen", Phone = "+1-555-0103" },
                        new { Id = 4, City = "Chicago", Company = "CloudNext", CreatedAt = new DateTime(2025, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "emily.davis@example.com", FirstName = "Emily", LastName = "Davis", Phone = "+1-555-0104" },
                        new { Id = 5, City = "Houston", Company = "FastTrack", CreatedAt = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "david.edwards@example.com", FirstName = "David", LastName = "Edwards", Phone = "+1-555-0105" },
                        new { Id = 6, City = "Phoenix", Company = "SecureNet", CreatedAt = new DateTime(2025, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "jessica.garcia@example.com", FirstName = "Jessica", LastName = "Garcia", Phone = "+1-555-0106" },
                        new { Id = 7, City = "Philadelphia", Company = "SmartBuild", CreatedAt = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "robert.harris@example.com", FirstName = "Robert", LastName = "Harris", Phone = "+1-555-0107" },
                        new { Id = 8, City = "San Antonio", Company = "VisionCore", CreatedAt = new DateTime(2025, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "amanda.johnson@example.com", FirstName = "Amanda", LastName = "Johnson", Phone = "+1-555-0108" },
                        new { Id = 9, City = "San Diego", Company = "FutureAI", CreatedAt = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "christopher.king@example.com", FirstName = "Christopher", LastName = "King", Phone = "+1-555-0109" },
                        new { Id = 10, City = "Dallas", Company = "PowerTech", CreatedAt = new DateTime(2025, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "victoria.lee@example.com", FirstName = "Victoria", LastName = "Lee", Phone = "+1-555-0110" },
                        new { Id = 11, City = "Austin", Company = "QuantumEdge", CreatedAt = new DateTime(2025, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "nathan.martinez@example.com", FirstName = "Nathan", LastName = "Martinez", Phone = "+1-555-0111" },
                        new { Id = 12, City = "Seattle", Company = "BrightPath", CreatedAt = new DateTime(2025, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "olivia.nelson@example.com", FirstName = "Olivia", LastName = "Nelson", Phone = "+1-555-0112" },
                        new { Id = 13, City = "Denver", Company = "NexaGroup", CreatedAt = new DateTime(2025, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "ethan.parker@example.com", FirstName = "Ethan", LastName = "Parker", Phone = "+1-555-0113" },
                        new { Id = 14, City = "Boston", Company = "AlphaLogic", CreatedAt = new DateTime(2025, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "sophia.quinn@example.com", FirstName = "Sophia", LastName = "Quinn", Phone = "+1-555-0114" },
                        new { Id = 15, City = "Miami", Company = "CoreWave", CreatedAt = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "liam.rivera@example.com", FirstName = "Liam", LastName = "Rivera", Phone = "+1-555-0115" },
                        new { Id = 16, City = "Atlanta", Company = "PinnacleIO", CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "isabella.scott@example.com", FirstName = "Isabella", LastName = "Scott", Phone = "+1-555-0116" },
                        new { Id = 17, City = "Portland", Company = "SkyLink", CreatedAt = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "mason.turner@example.com", FirstName = "Mason", LastName = "Turner", Phone = "+1-555-0117" },
                        new { Id = 18, City = "Minneapolis", Company = "GridForce", CreatedAt = new DateTime(2025, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "ava.underwood@example.com", FirstName = "Ava", LastName = "Underwood", Phone = "+1-555-0118" },
                        new { Id = 19, City = "Las Vegas", Company = "NovaSpark", CreatedAt = new DateTime(2025, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "logan.vasquez@example.com", FirstName = "Logan", LastName = "Vasquez", Phone = "+1-555-0119" },
                        new { Id = 20, City = "Nashville", Company = "ZenithTech", CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), Email = "mia.walsh@example.com", FirstName = "Mia", LastName = "Walsh", Phone = "+1-555-0120" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
